include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    exclude:
      - 'lib/**.g.dart'
      - 'lib/**.freezed.dart'
      - '../../lib/core/packages_injectable_module.dart'
