name: flutterence
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  # Firebase
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  google_sign_in: ^5.0.2
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  firebase_analytics: ^8.0.1
  injectable: ^1.2.2
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  auto_route: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  google_fonts: ^2.0.0

  #packages
  flutter_firebase_auth_facade: ^0.0.10-nullsafety.1
  user_repository:
      path: ./packages/user_repository
  firestore_helper:
      path: ./packages/firestore_helper
  push_notification:
      path: ./packages/push_notification

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0
  freezed: ^0.14.1+2
  injectable_generator: ^1.2.2
  json_serializable: ^4.1.1
  auto_route_generator: ^1.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
