name: flutterence

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test


      - name: Create env file
        env:
            SECRET_FILE: ${{ secrets.ENVS }}
        run: echo "$SECRET_FILE" | base64 --decode > .env


      - name: Check if generated file is not empty
        run: ls -l .env

      - name: cd to package firestore_helper
        run: |
          cd packages/firestore_helper
          pwd
      - name: Install dependencies
        run: flutter packages get
      - name: format
        run: flutter format --set-exit-if-changed lib test
      - name: Run build_runner
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze lib packages test
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: cd to Root project
            cd -
            pwd

      - name: Run build_runner in package group_repository
        run: |
            cd packages/group_repository
            pwd
      - name: Install dependencies
        run: flutter packages get
      - name: format
        run: flutter format --set-exit-if-changed lib test
      - name: Run build_runner
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze lib packages test
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: cd to Root project
            cd -
            pwd

      - name: Run build_runner in package user_repository
        run: |
            cd packages/user_repository
            pwd
      - name: Install dependencies
        run: flutter packages get
      - name: format
        run: flutter format --set-exit-if-changed lib test
      - name: Run build_runner
        run: |
            flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze lib packages test
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: cd to Root project
            cd -
            pwd

      - name: Run build_runner in project
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze lib packages test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: "lib/**.freezed.dart lib/**.g.dart"
